# Generated by Django 5.2 on 2025-05-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
    ]
